Fixed
Moved the check for the auth database outside of the check for parameters. The reason is that both the auth and world server needs access to it, but only the world need access to characters and world.

diff --git a/Bash/AzerothCore/core/source b/Bash/AzerothCore/core/source
--- a/Bash/AzerothCore/core/source
+++ b/Bash/AzerothCore/core/source
@@ -2205,20 +2205,20 @@ function import_database
     echo "user=\"$OPTION_MYSQL_USERNAME\"" >> $MYSQL_CNF
     echo "password=\"$OPTION_MYSQL_PASSWORD\"" >> $MYSQL_CNF
 
+    # Make sure the auth database exists and is accessible
+    if [ -z `mysql --defaults-extra-file=$MYSQL_CNF --skip-column-names -e "SHOW DATABASES LIKE '$OPTION_MYSQL_DATABASES_AUTH'"` ]; then
+        # We can't access the required database, so terminate the script
+        printf "\e[0;31mThe database named $OPTION_MYSQL_DATABASES_AUTH is inaccessible by the user named $OPTION_MYSQL_USERNAME.\e[0m\n"
+
+        # Remove the mysql conf
+        rm -rf $MYSQL_CNF
+
+        # Terminate script on error
+        exit $?
+    fi
+
     # Check if either both or auth is used as the first parameter
     if [[ $1 == "both" ]] || [[ $1 == "auth" ]]; then
-        # Make sure the auth database exists and is accessible
-        if [ -z `mysql --defaults-extra-file=$MYSQL_CNF --skip-column-names -e "SHOW DATABASES LIKE '$OPTION_MYSQL_DATABASES_AUTH'"` ]; then
-            # We can't access the required database, so terminate the script
-            printf "\e[0;31mThe database named $OPTION_MYSQL_DATABASES_AUTH is inaccessible by the user named $OPTION_MYSQL_USERNAME.\e[0m\n"
-
-            # Remove the mysql conf
-            rm -rf $MYSQL_CNF
-
-            # Terminate script on error
-            exit $?
-        fi
-
         # Make sure the database folders exists
         if [ ! -d $OPTION_SOURCE_LOCATION/data/sql/base/db_auth ] || [ ! -d $OPTION_SOURCE_LOCATION/data/sql/updates/db_auth ]; then
             # The files are missing, so terminate the script
